// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(EsnDevContext))]
    [Migration("20260117113658_AddEventFeedback")]
    partial class AddEventFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bo.Models.AdminBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Admins__3214EC07C94A3654");

                    b.HasIndex(new[] { "Email" }, "UQ__Admins__A9D105348FC7749F")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Bo.Models.CalendarBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("EventManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("MainOrganizerId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsableComId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Calendars__3214EC07");

                    b.HasIndex("EventId");

                    b.HasIndex("EventManagerId");

                    b.HasIndex("MainOrganizerId");

                    b.HasIndex("ResponsableComId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("Bo.Models.CalendarSubOrganizerBo", b =>
                {
                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CalendarId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CalendarSubOrganizers");
                });

            modelBuilder.Entity("Bo.Models.EventBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EventfrogLink")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("FeedbackDeadline")
                        .HasColumnType("datetime");

                    b.Property<string>("FeedbackFormData")
                        .HasMaxLength(100000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SurveyJsData")
                        .HasMaxLength(100000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Events__3214EC079399E819");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Bo.Models.EventFeedbackBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FeedbackData")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__EventFeedback__3214EC07");

                    b.HasIndex("EventId");

                    b.HasIndex(new[] { "UserId", "EventId" }, "UQ_EventFeedback_User_Event")
                        .IsUnique();

                    b.ToTable("EventFeedbacks");
                });

            modelBuilder.Entity("Bo.Models.EventRegistrationBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AttendanceValidatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("AttendanceValidatedById")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("registered");

                    b.Property<string>("SurveyJsData")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__EventReg__3214EC07FA5EB91B");

                    b.HasIndex("AttendanceValidatedById");

                    b.HasIndex("EventId");

                    b.HasIndex(new[] { "UserId", "EventId" }, "UQ_Registration")
                        .IsUnique();

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("Bo.Models.EventTemplateBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SurveyJsData")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__EventTemplate__3214EC07");

                    b.ToTable("EventTemplates");
                });

            modelBuilder.Entity("Bo.Models.PropositionBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VotesDown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("VotesUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Propositions__3214EC07");

                    b.HasIndex("UserId");

                    b.ToTable("Propositions");
                });

            modelBuilder.Entity("Bo.Models.PropositionVoteBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PropositionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VoteType")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PropositionVotes__3214EC07");

                    b.HasIndex("PropositionId");

                    b.HasIndex(new[] { "UserId", "PropositionId" }, "UQ_PropositionVotes_User_Proposition")
                        .IsUnique();

                    b.ToTable("PropositionVotes");
                });

            modelBuilder.Entity("Bo.Models.RoleBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreateEvents")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateUsers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteEvents")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteUsers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanModifyEvents")
                        .HasColumnType("bit");

                    b.Property<bool>("CanModifyUsers")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Bo.Models.UserBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EsnCardNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ESNCardNumber");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TransportPass")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC076FF3256C");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340768CBC8")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bo.Models.CalendarBo", b =>
                {
                    b.HasOne("Bo.Models.EventBo", "Event")
                        .WithMany("Calendars")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Calendars_Events");

                    b.HasOne("Bo.Models.UserBo", "EventManager")
                        .WithMany()
                        .HasForeignKey("EventManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Calendars_EventManager");

                    b.HasOne("Bo.Models.UserBo", "MainOrganizer")
                        .WithMany()
                        .HasForeignKey("MainOrganizerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Calendars_MainOrganizer");

                    b.HasOne("Bo.Models.UserBo", "ResponsableCom")
                        .WithMany()
                        .HasForeignKey("ResponsableComId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Calendars_ResponsableCom");

                    b.Navigation("Event");

                    b.Navigation("EventManager");

                    b.Navigation("MainOrganizer");

                    b.Navigation("ResponsableCom");
                });

            modelBuilder.Entity("Bo.Models.CalendarSubOrganizerBo", b =>
                {
                    b.HasOne("Bo.Models.CalendarBo", "Calendar")
                        .WithMany("CalendarSubOrganizers")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CalendarSubOrganizers_Calendars");

                    b.HasOne("Bo.Models.UserBo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CalendarSubOrganizers_Users");

                    b.Navigation("Calendar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bo.Models.EventBo", b =>
                {
                    b.HasOne("Bo.Models.UserBo", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Events_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bo.Models.EventFeedbackBo", b =>
                {
                    b.HasOne("Bo.Models.EventBo", "Event")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventFeedback_Events");

                    b.HasOne("Bo.Models.UserBo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventFeedback_Users");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bo.Models.EventRegistrationBo", b =>
                {
                    b.HasOne("Bo.Models.UserBo", "AttendanceValidatedBy")
                        .WithMany()
                        .HasForeignKey("AttendanceValidatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Registrations_AttendanceValidator");

                    b.HasOne("Bo.Models.EventBo", "Event")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Registrations_Events");

                    b.HasOne("Bo.Models.UserBo", "User")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Registrations_Users");

                    b.Navigation("AttendanceValidatedBy");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bo.Models.PropositionBo", b =>
                {
                    b.HasOne("Bo.Models.UserBo", "User")
                        .WithMany("Propositions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Propositions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bo.Models.PropositionVoteBo", b =>
                {
                    b.HasOne("Bo.Models.PropositionBo", "Proposition")
                        .WithMany("Votes")
                        .HasForeignKey("PropositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PropositionVotes_Propositions");

                    b.HasOne("Bo.Models.UserBo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PropositionVotes_Users");

                    b.Navigation("Proposition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bo.Models.UserBo", b =>
                {
                    b.HasOne("Bo.Models.RoleBo", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Bo.Models.CalendarBo", b =>
                {
                    b.Navigation("CalendarSubOrganizers");
                });

            modelBuilder.Entity("Bo.Models.EventBo", b =>
                {
                    b.Navigation("Calendars");

                    b.Navigation("EventRegistrations");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Bo.Models.PropositionBo", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Bo.Models.RoleBo", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Bo.Models.UserBo", b =>
                {
                    b.Navigation("EventRegistrations");

                    b.Navigation("Events");

                    b.Navigation("Propositions");
                });
#pragma warning restore 612, 618
        }
    }
}
